import React from "react";

export default function ExportView({ zones, cells, gridSize }) {
  return (
    <div
      id="export-target"
      style={{
        width: 600,
        padding: 24,
        background: "#f8f9fa",
        fontFamily: "sans-serif",
      }}
    >
      {/* タイトル */}
      <h2 style={{ textAlign: "center", marginBottom: 16 }}>
        🏝 あつ森 島レイアウト
      </h2>

      {/* グリッド */}
      <div
        style={{
          display: "grid",
          gridTemplateColumns: `repeat(${gridSize}, 1fr)`,
          gap: 2,
          background: "#ccc",
          padding: 4,
        }}
      >
        {Array.from({ length: gridSize * gridSize }).map((_, i) => {
          const zone = zones.find(z => z.id === cells[i]);
          return (
            <div
              key={i}
              style={{
                width: 40,
                height: 40,
                background: zone ? zone.color : "#fff",
                border: "1px solid #ddd",
              }}
            />
          );
        })}
      </div>

      {/* 凡例 */}
      <div style={{ marginTop: 16 }}>
        {zones.map(zone => (
          <div key={zone.id} style={{ display: "flex", alignItems: "center" }}>
            <div
              style={{
                width: 16,
                height: 16,
                background: zone.color,
                marginRight: 8,
              }}
            />
            <span>{zone.name}</span>
          </div>
        ))}
      </div>

      {/* フッター */}
      <div
        style={{
          marginTop: 16,
          fontSize: 12,
          color: "#888",
          textAlign: "center",
        }}
      >
        Generated by Island Planner
      </div>
    </div>
  );
}
